#!/bin/bash

if ! grep -q "\[chaotic-aur\]" /etc/pacman.conf; then
    echo "Chaotic-AUR repository not found. Adding it now..."
else
    echo "Chaotic-AUR repository already exists. Skipping..."
    exit 0
fi

# Add the chaotic-aur repository and its keyring
sudo pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
sudo pacman-key --lsign-key 3056513887B78AEB

sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
sudo pacman -U 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

# Add the chaotic-aur repository to pacman.conf
echo -e "\n[chaotic-aur]\nInclude = /etc/pacman.d/chaotic-mirrorlist" | sudo tee -a /etc/pacman.conf

# Update the package database and upgrade the system
sudo pacman -Syu